package com.example.demo.types;

public enum NotificationType {

    NEW_FOLLOW,

    TRACK_LIKE,
    TRACK_COMMENT,

    TRACK_APPROVED,
    TRACK_REJECTED,

    COPYRIGHT_APPROVED,
    COPYRIGHT_REJECTED,

    TRACK_PROCESSING_COMPLETED,

    UPLOAD_QUOTA_WARNING,
    UPLOAD_QUOTA_EXCEEDED,

    SUBSCRIPTION_CHANGED,
    SUBSCRIPTION_CANCEL_SCHEDULED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_EXPIRING,

    SYSTEM
}