name: soundclone_mobile
description: "SoundClone mobile application."
publish_to: "none"

# Phiên bản ứng dụng:
# 1.0.0 = versionName
# 1 = versionCode
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  # Icon theo phong cách iOS.
  cupertino_icons: ^1.0.8

  # HTTP client được sử dụng trong api_service.dart.
  http: ^1.6.0

  # HTTP client nâng cao.
  # Giữ lại để sử dụng cho interceptor hoặc download/upload nâng cao sau này.
  dio: ^5.10.0

  # State management cho toàn bộ ứng dụng.
  flutter_riverpod: ^3.3.2

  # Điều hướng giữa các màn hình.
  go_router: ^17.3.0

  # Lưu access token và refresh token an toàn trên thiết bị.
  flutter_secure_storage: ^10.3.1

  # Chọn avatar và ảnh bìa từ thư viện ảnh/camera của thiết bị.
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Bộ quy tắc kiểm tra và chuẩn hóa code Flutter.
  flutter_lints: ^6.0.0

flutter:
  # Cho phép sử dụng Material Icons.
  uses-material-design: true
