package com.example.demo.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Track generated by hbm2java
 */
@Entity
@Table(name = "tracks")
public class Track implements java.io.Serializable {

	private String id;
	private String title;
	private String description;
	private String category;
	private String imgUrl;
	private String trackUrl;
	private Integer countLike;
	private Integer countPlay;
	private String uploaderId;
	private Boolean isDeleted;
	private Date createdAt;
	private Date updatedAt;

	private User uploader;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Playlist> playlists = new HashSet<Playlist>(0);
	private Set<User> likedByUsers = new HashSet<User>(0);

	public Track() {
	}

	public Track(String id, String title) {
		this.id = id;
		this.title = title;
	}

	public Track(String id, String title, String description, String category, String imgUrl, String trackUrl,
			Integer countLike, Integer countPlay, String uploaderId, Boolean isDeleted, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.category = category;
		this.imgUrl = imgUrl;
		this.trackUrl = trackUrl;
		this.countLike = countLike;
		this.countPlay = countPlay;
		this.uploaderId = uploaderId;
		this.isDeleted = isDeleted;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 24)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "category", length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "imgUrl", length = 500)
	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	@Column(name = "trackUrl", length = 500)
	public String getTrackUrl() {
		return this.trackUrl;
	}

	public void setTrackUrl(String trackUrl) {
		this.trackUrl = trackUrl;
	}

	@Column(name = "countLike")
	public Integer getCountLike() {
		return this.countLike;
	}

	public void setCountLike(Integer countLike) {
		this.countLike = countLike;
	}

	@Column(name = "countPlay")
	public Integer getCountPlay() {
		return this.countPlay;
	}

	public void setCountPlay(Integer countPlay) {
		this.countPlay = countPlay;
	}

	@Column(name = "uploaderId", length = 24)
	public String getUploaderId() {
		return this.uploaderId;
	}

	public void setUploaderId(String uploaderId) {
		this.uploaderId = uploaderId;
	}

	@Column(name = "isDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedAt", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uploaderId", insertable = false, updatable = false)
	public User getUploader() {
		return this.uploader;
	}

	public void setUploader(User uploader) {
		this.uploader = uploader;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "track")
	@JsonManagedReference
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "likedTracks")
	@JsonIgnore
	public Set<User> getLikedByUsers() {
		return this.likedByUsers;
	}

	public void setLikedByUsers(Set<User> likedByUsers) {
		this.likedByUsers = likedByUsers;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tracks")
	@JsonIgnore
	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}
}