package com.example.demo.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "users", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class User implements java.io.Serializable {

	private String id;
	private String email;
	private String username;
	private String password;
	private String name;
	private String role;
	private Integer age;
	private String gender;
	private Boolean isVerify;
	private String type;
	private String code;
	private Date codeExpired;
	private String refreshToken;
	private String avatarUrl;
	private Integer followers;
	private Integer following;
	private String coverUrl;
	private String bio;
	private String website;
	private Date createdAt;
	private Date updatedAt;
	private String city;
	private String country;
	private Boolean verified;
	private String spotlightTrackId;
	private String subscriptionTier;
	private Set<Track> uploadedTracks = new HashSet<Track>(0);
	private Set<Playlist> playlists = new HashSet<Playlist>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Track> likedTracks = new HashSet<Track>(0);

	private String accountStatus = "ACTIVE";
	private String statusReason;
	private Date suspendedUntil;
	private Date statusUpdatedAt;
	/*
	 * =========================
	 * CHAT STATUS
	 * =========================
	 */
	private String chatStatus = "ACTIVE";
	private String chatBanReason;
	private Date chatStatusUpdatedAt;

	public String getSubscriptionTier() {
		return subscriptionTier;
	}

	public void setSubscriptionTier(String subscriptionTier) {
		this.subscriptionTier = subscriptionTier;
	}

	public User() {
	}

	public User(String id, String email) {
		this.id = id;
		this.email = email;
	}

	public User(String id, String email, String username, String password, String name, String role,
			Integer age, String gender, Boolean isVerify, String type, String code, String refreshToken, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.email = email;
		this.username = username;
		this.password = password;
		this.name = name;
		this.role = role;
		this.age = age;
		this.gender = gender;
		this.isVerify = isVerify;
		this.type = type;
		this.code = code;
		this.refreshToken = refreshToken;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 24)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "email", unique = true, nullable = false, length = 255)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", length = 255)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 255)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", length = 255)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role", length = 100)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getCoverUrl() {
		return coverUrl;
	}

	public void setCoverUrl(String coverUrl) {
		this.coverUrl = coverUrl;
	}

	public String getBio() {
		return bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Boolean getVerified() {
		return verified;
	}

	public void setVerified(Boolean verified) {
		this.verified = verified;
	}

	public String getSpotlightTrackId() {
		return spotlightTrackId;
	}

	public void setSpotlightTrackId(String spotlightTrackId) {
		this.spotlightTrackId = spotlightTrackId;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "gender", length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "is_verify")
	public Boolean getIsVerify() {
		return this.isVerify;
	}

	public void setIsVerify(Boolean isVerify) {
		this.isVerify = isVerify;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "code", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "code_expired")
	public Date getCodeExpired() {
		return codeExpired;
	}

	public void setCodeExpired(Date codeExpired) {
		this.codeExpired = codeExpired;
	}

	@Column(name = "refresh_token")
	public String getRefreshToken() {
		return this.refreshToken;
	}

	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken;
	}

	@Column(name = "avatar_url", length = 500)
	public String getAvatarUrl() {
		return avatarUrl;
	}

	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	public Integer getFollowers() {
		return followers;
	}

	public void setFollowers(Integer followers) {
		this.followers = followers;
	}

	public Integer getFollowing() {
		return following;
	}

	public void setFollowing(Integer following) {
		this.following = following;
	}

	@Column(name = "created_at")
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "updated_at")
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "uploader")
	@JsonIgnore
	public Set<Track> getUploadedTracks() {
		return this.uploadedTracks;
	}

	public void setUploadedTracks(Set<Track> uploadedTracks) {
		this.uploadedTracks = uploadedTracks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_liked_tracks", joinColumns = {
			@JoinColumn(name = "userId", nullable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "trackId", nullable = false) })
	public Set<Track> getLikedTracks() {
		return this.likedTracks;
	}

	public void setLikedTracks(Set<Track> likedTracks) {
		this.likedTracks = likedTracks;
	}

	@Column(name = "account_status", length = 20)
	public String getAccountStatus() {
		if (accountStatus == null || accountStatus.isBlank()) {
			return "ACTIVE";
		}

		return accountStatus;
	}

	public void setAccountStatus(String accountStatus) {
		if (accountStatus == null || accountStatus.isBlank()) {
			this.accountStatus = "ACTIVE";
			return;
		}

		this.accountStatus = accountStatus.trim().toUpperCase();
	}

	@Column(name = "status_reason", length = 500)
	public String getStatusReason() {
		return statusReason;
	}

	public void setStatusReason(String statusReason) {
		this.statusReason = statusReason;
	}

	@Column(name = "suspended_until")
	public Date getSuspendedUntil() {
		return suspendedUntil;
	}

	public void setSuspendedUntil(Date suspendedUntil) {
		this.suspendedUntil = suspendedUntil;
	}

	@Column(name = "status_updated_at")
	public Date getStatusUpdatedAt() {
		return statusUpdatedAt;
	}

	public void setStatusUpdatedAt(Date statusUpdatedAt) {
		this.statusUpdatedAt = statusUpdatedAt;
	}

	@Column(name = "chat_status", length = 20)
	public String getChatStatus() {
		if (chatStatus == null || chatStatus.isBlank()) {
			return "ACTIVE";
		}

		return chatStatus;
	}

	public void setChatStatus(String chatStatus) {
		if (chatStatus == null || chatStatus.isBlank()) {
			this.chatStatus = "ACTIVE";
			return;
		}

		this.chatStatus = chatStatus.trim().toUpperCase();
	}

	@Column(name = "chat_ban_reason", length = 500)
	public String getChatBanReason() {
		return chatBanReason;
	}

	public void setChatBanReason(String chatBanReason) {
		this.chatBanReason = chatBanReason;
	}

	@Column(name = "chat_status_updated_at")
	public Date getChatStatusUpdatedAt() {
		return chatStatusUpdatedAt;
	}

	public void setChatStatusUpdatedAt(Date chatStatusUpdatedAt) {
		this.chatStatusUpdatedAt = chatStatusUpdatedAt;
	}
}